<form method="POST" class="card needs-validation main" novalidate>
    <?= $form->csrfField('noob'); ?>
    <div class="card-header">
        Change Password
        <div class="float-right">
            <button class="btn btn-primary">Save</button>
        </div>
    </div>
    <div class="card-body">
        <?php if($success): ?>
            <div class="alert alert-success" role="alert">
                Your password successfully updated.
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-5">
                <?= $form->field('old-password'); ?>
                <hr>
                <?= $form->field('new-password'); ?>
                <?= $form->field('retype-password'); ?>
            </div>
        </div>
    </div>
</form>