<form method="POST" class="card needs-validation main" novalidate>
    <?= $form->csrfField('noob'); ?>
    <div class="card-header">
        Edit Profile
        <div class="float-right">
            <button class="btn btn-primary">Save</button>
        </div>
    </div>
    <div class="card-body">
        <?php if($success): ?>
            <div class="alert alert-success" role="alert">
                Your profile successfully updated.
            </div>
        <?php endif; ?>
        <div class="row">
            <?php if(isset($fields['left'])): ?>
            <div class="col-md-4">
                <?php foreach($fields['left'] as $field): ?>
                    <?= $form->field($field); ?>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
            <?php if(isset($fields['center'])): ?>
            <div class="col-md-4">
                <?php foreach($fields['center'] as $field): ?>
                    <?= $form->field($field); ?>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
            <?php if(isset($fields['right'])): ?>
            <div class="col-md-4">
                <?php foreach($fields['right'] as $field): ?>
                    <?= $form->field($field); ?>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
        </div>
        <?php if(isset($fields['bottom'])): ?>  
        <div class="row">
            <div class="col-md-12">
                <?php foreach($fields['bottom'] as $field): ?>
                    <?= $form->field($field); ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</form>